// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkB-HizyOLy7YM7fGV2BFfI07hY9nIZNA',
    appId: '1:900309403248:web:0843c6484cb23b5622d6b5',
    messagingSenderId: '900309403248',
    projectId: 'scholar-scraper-app',
    authDomain: 'scholar-scraper-app.firebaseapp.com',
    storageBucket: 'scholar-scraper-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJ8vQanYPXCf4CQN6a7MA4Ibezl2nLF0',
    appId: '1:900309403248:android:ac23cf062a416aed22d6b5',
    messagingSenderId: '900309403248',
    projectId: 'scholar-scraper-app',
    storageBucket: 'scholar-scraper-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb11kUx7P3XaMdUJas299NJYG8s9DQm-c',
    appId: '1:900309403248:ios:de7a4199990de85422d6b5',
    messagingSenderId: '900309403248',
    projectId: 'scholar-scraper-app',
    storageBucket: 'scholar-scraper-app.appspot.com',
    iosBundleId: 'com.example.scholarScraperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb11kUx7P3XaMdUJas299NJYG8s9DQm-c',
    appId: '1:900309403248:ios:6a5e6f2205d94a4222d6b5',
    messagingSenderId: '900309403248',
    projectId: 'scholar-scraper-app',
    storageBucket: 'scholar-scraper-app.appspot.com',
    iosBundleId: 'com.example.scholarScraperApp.RunnerTests',
  );
}
